version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: "events"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - events

networks:
  events:
    driver: bridge
